language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-image -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "new-app"
  env: "Newapp-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-055596350215"
  bucket_path: "new-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
