version: '3'

services: 
  app:
    ports:
      - "8080:3000"
    environment: 
      - "CHOKIDAR_USEPOLLING=true"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]  